name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up JDK 11 (if applicable for your app)
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      # Step 3: Build with Maven (if applicable for your app)
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      # Step 5: Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/genai-project .

      # Step 6: Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/genai-project

      # Step 7: Log out from Docker Hub
      - name: Log out from Docker Hub
        run: docker logout

      # Step 8: Log in to Heroku Container Registry
      - name: Log in to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "${{ secrets.HEROKU_API_KEY }}" | docker login --username=_ --password-stdin registry.heroku.com

      # Step 9: Tag and Push Docker image to Heroku
      - name: Build and Push Docker image to Heroku
        run: |
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/genai-project registry.heroku.com/genaiproject/web
          docker push registry.heroku.com/genaiproject/web

      # Step 10: Set the Heroku app stack to "container" (if needed)
      - name: Set Heroku stack to container
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku stack:set container --app genaiproject

      # Step 11: Release the Docker image on Heroku
      - name: Release the Docker image on Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release web --app genaiproject

      # Step 12: Log out from Heroku
      - name: Log out from Heroku
        run: docker logout registry.heroku.com