name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/genai-project .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/genai-project

      - name: Log out from Docker Hub
        run: docker logout

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Log in to Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Run Docker container
        run: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/genai-project
          docker run -d -p 80:8080 \
            -e CHATGPT_API_KEY=${{ secrets.CHATGPT_API_KEY }} \
            -e CHATGPT_API_URL=${{ secrets.CHATGPT_API_URL }} \
            ${{ secrets.DOCKER_HUB_USERNAME }}/genai-project

      - name: Log out from Docker Hub
        run: docker logout